/**
* packetcapture API generated from packetcapture.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/PacketcaptureApiImpl.h"
#include "../datamodel/packetcapture.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "master/d9c5120"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return packetcapture_datamodel.c_str();
}
