/**
* packetcapture API generated from packetcapture.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "Filters.h"
#include "Packetcapture.h"


Filters::Filters(Packetcapture &parent, const FiltersJsonObject &conf)
    : FiltersBase(parent) {
  if (conf.snaplenIsSet()) {
    setSnaplen(conf.getSnaplen());
  }

  if (conf.srcIsSet()) {
    setSrc(conf.getSrc());
  }

  if (conf.dstIsSet()) {
    setDst(conf.getDst());
  }

  if (conf.l4protoIsSet()) {
    setL4proto(conf.getL4proto());
  }

  if (conf.sportIsSet()) {
    setSport(conf.getSport());
  }

  if (conf.dportIsSet()) {
    setDport(conf.getDport());
  }

}

Filters::~Filters() {}

uint32_t Filters::getSnaplen() {
  throw std::runtime_error("Filters::getSnaplen: Method not implemented");
}

void Filters::setSnaplen(const uint32_t &value) {
  throw std::runtime_error("Filters::setSnaplen: Method not implemented");
}

std::string Filters::getSrc() {
  throw std::runtime_error("Filters::getSrc: Method not implemented");
}

void Filters::setSrc(const std::string &value) {
  throw std::runtime_error("Filters::setSrc: Method not implemented");
}

std::string Filters::getDst() {
  throw std::runtime_error("Filters::getDst: Method not implemented");
}

void Filters::setDst(const std::string &value) {
  throw std::runtime_error("Filters::setDst: Method not implemented");
}

std::string Filters::getL4proto() {
  throw std::runtime_error("Filters::getL4proto: Method not implemented");
}

void Filters::setL4proto(const std::string &value) {
  throw std::runtime_error("Filters::setL4proto: Method not implemented");
}

uint16_t Filters::getSport() {
  throw std::runtime_error("Filters::getSport: Method not implemented");
}

void Filters::setSport(const uint16_t &value) {
  throw std::runtime_error("Filters::setSport: Method not implemented");
}

uint16_t Filters::getDport() {
  throw std::runtime_error("Filters::getDport: Method not implemented");
}

void Filters::setDport(const uint16_t &value) {
  throw std::runtime_error("Filters::setDport: Method not implemented");
}


