/**
* packetcapture API generated from packetcapture.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/GlobalheaderBase.h"


class Packetcapture;

using namespace polycube::service::model;

class Globalheader : public GlobalheaderBase {

  uint32_t snaplen;

 public:
  Globalheader(Packetcapture &parent, const GlobalheaderJsonObject &conf);
  virtual ~Globalheader();

  /// <summary>
  /// magic number
  /// </summary>
  uint32_t getMagic() override;
  void setMagic(const uint32_t &value) override;

  /// <summary>
  /// major version number
  /// </summary>
  uint16_t getVersionMajor() override;
  void setVersionMajor(const uint16_t &value) override;

  /// <summary>
  /// minor version number
  /// </summary>
  uint16_t getVersionMinor() override;
  void setVersionMinor(const uint16_t &value) override;

  /// <summary>
  /// GMT to local correction
  /// </summary>
  int32_t getThiszone() override;
  void setThiszone(const int32_t &value) override;

  /// <summary>
  /// accuracy of timestamps
  /// </summary>
  uint32_t getSigfigs() override;
  void setSigfigs(const uint32_t &value) override;

  /// <summary>
  /// max length of captured packets, in octets
  /// </summary>
  uint32_t getSnaplen() override;
  void setSnaplen(const uint32_t &value) override;

  /// <summary>
  /// Capture linktype (eg. ethernet, wifi..)
  /// </summary>
  uint32_t getLinktype() override;
  void setLinktype(const uint32_t &value) override;
};
