/**
* packetcapture API generated from packetcapture.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#include "Packet.h"
#include "Packetcapture.h"


Packet::Packet(Packetcapture &parent, const PacketJsonObject &conf)
    : PacketBase(parent), capture_len(0), packet_len(0), ts_microsec(0), ts_sec(0) {
  if (conf.capturelenIsSet()) {
    setCapturelen(conf.getCapturelen());
  }

  if (conf.packetlenIsSet()) {
    setPacketlen(conf.getPacketlen());
  }

  if (conf.timestampSecondsIsSet()) {
    setTimestampSeconds(conf.getTimestampSeconds());
  }

  if (conf.timestampMicrosecondsIsSet()) {
    setTimestampMicroseconds(conf.getTimestampMicroseconds());
  }

}


Packet::~Packet() {}

uint32_t Packet::getCapturelen() {
  return this->capture_len;
}

void Packet::setCapturelen(const uint32_t &value) {
  this->capture_len = value;
}

uint32_t Packet::getPacketlen() {
  return this->packet_len;
}

void Packet::setPacketlen(const uint32_t &value) {
  this->packet_len = value;
}

uint32_t Packet::getTimestampSeconds() {
  return this->ts_sec;
}

void Packet::setTimestampSeconds(const uint32_t &value) {
  this->ts_sec = value;
}

uint32_t Packet::getTimestampMicroseconds() {
  return this->ts_microsec;
}

void Packet::setTimestampMicroseconds(const uint32_t &value) {
  this->ts_microsec = value;
}


